import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { restoreBackingFillMarkers } from "../scripts/browser-harness/pawn-backing-fill-markers";

/**
 * Integrity of the pawn art shipped in `frontend/public/`. Consolidated from
 * pawn-backings.test.ts, animal-pawn-assets.test.ts and
 * pawn-backing-fill-markers.test.ts.
 *
 * The dog and elephant sets are purchased art, imported and sanitized by the
 * scripts/browser-harness pipeline (process-animal-pawns.ts). Nothing upstream
 * regenerates these directories, so these tests are what notices a design
 * going missing, a combined sheet slipping in, or an unsanitized re-export.
 * The sanitation gate pins the pipeline's output to pure local path geometry:
 * a <script>, <style>, <use>, <image>, event handler, href= or url(...) in a
 * purchased SVG is content that reaches outside the file - at best it renders
 * as a blank pawn inside an <img>, at worst it executes if the markup is ever
 * inlined or the file opened directly.
 *
 * The backing PNGs are generated by
 * scripts/browser-harness/generate-pawn-backings.ts; every SVG must have one,
 * or PawnImage layers a 404 behind the pawn. The puppy SVGs carry a
 * `data-pawn-backing-fill="white"` marker on paths that render transparent at
 * runtime but must count as solid white when the backing is generated.
 * Restoration matches the exact attribute order `fill="none"
 * data-pawn-backing-fill="white"`, so if a re-export ever reorders those
 * attributes the generator must STOP rather than silently emit a hollowed-out
 * backing.
 */

const ROOT = path.resolve(import.meta.dir, "..");
const PAWN_TYPES = ["dog", "cat", "mouse", "elephant", "home"] as const;

const svgNames = (type: (typeof PAWN_TYPES)[number]) =>
  readdirSync(path.join(ROOT, "frontend/public/pawns", type))
    .filter((name) => name.endsWith(".svg"))
    .sort();

describe("purchased animal pawn completeness and sanitation", () => {
  test("contains every numbered individual design and no combined sheet", () => {
    expect(svgNames("dog")).toEqual(
      [
        ...Array.from(
          { length: 24 },
          (_, index) =>
            `dog-one-line-${String(index + 2).padStart(2, "0")}.svg`,
        ),
        ...Array.from(
          { length: 25 },
          (_, index) => `dog-puppy-${String(index + 1).padStart(2, "0")}.svg`,
        ),
      ].sort(),
    );
    expect(svgNames("elephant")).toEqual(
      Array.from(
        { length: 25 },
        (_, index) => `elephant-${String(index + 1).padStart(2, "0")}.svg`,
      ),
    );
  });

  test("contains only sanitized local path geometry", () => {
    for (const type of ["dog", "elephant"] as const) {
      for (const name of svgNames(type)) {
        const svg = readFileSync(
          path.join(ROOT, "frontend/public/pawns", type, name),
          "utf8",
        );
        expect(svg).not.toMatch(
          /<script|<style|<image|<use|<defs|foreignObject|\bon\w+=|\bhref=|url\s*\(/i,
        );
        expect(svg).toMatch(/^<svg [^>]*viewBox="[^"]+"[^>]*>/);
        expect(svg).toContain("<path");
      }
    }
  });
});

describe("generated pawn backings", () => {
  for (const type of PAWN_TYPES) {
    test(`${type} has one backing for every SVG`, () => {
      const sourceNames = svgNames(type)
        .map((name) => name.replace(/\.svg$/, ".png"))
        .sort();
      const backingNames = readdirSync(
        path.join(ROOT, "frontend/public/pawn-backings", type),
      )
        .filter((name) => name.endsWith(".png"))
        .sort();

      expect(backingNames).toEqual(sourceNames);
    });
  }
});

describe("Puppy backing-fill marker restoration", () => {
  test("known-bad attribute drift stops instead of hollowing the backing", () => {
    expect(() =>
      restoreBackingFillMarkers(
        '<path data-pawn-backing-fill="white" fill="none"/>',
        "drifted.svg",
      ),
    ).toThrow("drifted.svg: 1 backing-fill marker(s) were not restored");
  });
});
