#!/bin/bash
# Calculate ELO ratings from tournament results using BayesElo
#
# This script processes the PGN files generated by the tournament
# and calculates ELO ratings for each model

set -e

TOURNAMENT_DIR="../tournament_results_universal"
BAYESELO_PATH="../../bayeselo/src/bayeselo"

# Check if BayesElo exists
if [ ! -f "$BAYESELO_PATH" ]; then
    echo "ERROR: BayesElo not found at $BAYESELO_PATH"
    echo ""
    echo "Expected location: ../bayeselo/src/bayeselo (relative to wallgame repo)"
    echo ""
    echo "If BayesElo is installed elsewhere, please update BAYESELO_PATH in this script"
    exit 1
fi

# Function to calculate ELO for a variant
calculate_variant_elo() {
    local variant=$1
    local pgn_file="$TOURNAMENT_DIR/$variant/games.pgn"
    local output_csv="$TOURNAMENT_DIR/$variant/elo_ratings.csv"
    local output_txt="$TOURNAMENT_DIR/$variant/elo_ratings.txt"

    if [ ! -f "$pgn_file" ]; then
        echo "ERROR: PGN file not found: $pgn_file"
        echo "Did you run the tournament for $variant variant?"
        return 1
    fi

    echo "=========================================="
    echo "Calculating ELO for $variant variant"
    echo "=========================================="
    echo "Input: $pgn_file"
    echo "Processing..."
    echo ""

    # Create BayesElo command file
    cat > /tmp/bayeselo_commands_$variant.txt << EOF
readpgn $pgn_file
elo
mm
exactdist
ratings >$output_txt
offset 1500
ratings >$output_csv
x
EOF

    # Run BayesElo
    $BAYESELO_PATH < /tmp/bayeselo_commands_$variant.txt

    echo ""
    echo "Results saved to:"
    echo "  Text: $output_txt"
    echo "  CSV:  $output_csv"
    echo ""

    # Display top 10 models
    echo "Top 10 models for $variant variant:"
    echo "----------------------------------------"
    head -13 "$output_txt" | tail -10
    echo "----------------------------------------"
    echo ""

    # Clean up
    rm /tmp/bayeselo_commands_$variant.txt
}

# Check which variants have results
echo "Checking for tournament results..."
echo ""

VARIANTS_TO_PROCESS=()

if [ -f "$TOURNAMENT_DIR/standard/games.pgn" ]; then
    echo "✓ Standard variant results found"
    VARIANTS_TO_PROCESS+=("standard")
else
    echo "✗ Standard variant results not found"
fi

if [ -f "$TOURNAMENT_DIR/classic/games.pgn" ]; then
    echo "✓ Classic variant results found"
    VARIANTS_TO_PROCESS+=("classic")
else
    echo "✗ Classic variant results not found"
fi

echo ""

if [ ${#VARIANTS_TO_PROCESS[@]} -eq 0 ]; then
    echo "ERROR: No tournament results found!"
    echo "Please run the tournament first: ./run_universal_tournament.sh"
    exit 1
fi

# Process each variant
for variant in "${VARIANTS_TO_PROCESS[@]}"; do
    calculate_variant_elo "$variant"
done

echo "=========================================="
echo "ELO CALCULATION COMPLETE!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review ratings in: $TOURNAMENT_DIR/{standard,classic}/elo_ratings.txt"
echo "2. Plot ELO progression (optional):"
echo "   cd scripts"
echo "   python plot_elo.py $TOURNAMENT_DIR/standard/elo_ratings.csv --output ../tournament_results_universal/standard_elo.png"
echo "   python plot_elo.py $TOURNAMENT_DIR/classic/elo_ratings.csv --output ../tournament_results_universal/classic_elo.png"
echo ""
