/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyBoardRouteImport } from './routes/study-board'
import { Route as SoloCampaignRouteImport } from './routes/solo-campaign'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PastGamesRouteImport } from './routes/past-games'
import { Route as LiveGamesRouteImport } from './routes/live-games'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GameSetupRouteImport } from './routes/game-setup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoloCampaignIdRouteImport } from './routes/solo-campaign.$id'
import { Route as PuzzlesIdRouteImport } from './routes/puzzles.$id'
import { Route as GameIdRouteImport } from './routes/game.$id'

const StudyBoardRoute = StudyBoardRouteImport.update({
  id: '/study-board',
  path: '/study-board',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloCampaignRoute = SoloCampaignRouteImport.update({
  id: '/solo-campaign',
  path: '/solo-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PastGamesRoute = PastGamesRouteImport.update({
  id: '/past-games',
  path: '/past-games',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveGamesRoute = LiveGamesRouteImport.update({
  id: '/live-games',
  path: '/live-games',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSetupRoute = GameSetupRouteImport.update({
  id: '/game-setup',
  path: '/game-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloCampaignIdRoute = SoloCampaignIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SoloCampaignRoute,
} as any)
const PuzzlesIdRoute = PuzzlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PuzzlesRoute,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game-setup': typeof GameSetupRoute
  '/learn': typeof LearnRoute
  '/live-games': typeof LiveGamesRoute
  '/past-games': typeof PastGamesRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/solo-campaign': typeof SoloCampaignRouteWithChildren
  '/study-board': typeof StudyBoardRoute
  '/game/$id': typeof GameIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/solo-campaign/$id': typeof SoloCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game-setup': typeof GameSetupRoute
  '/learn': typeof LearnRoute
  '/live-games': typeof LiveGamesRoute
  '/past-games': typeof PastGamesRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/solo-campaign': typeof SoloCampaignRouteWithChildren
  '/study-board': typeof StudyBoardRoute
  '/game/$id': typeof GameIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/solo-campaign/$id': typeof SoloCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game-setup': typeof GameSetupRoute
  '/learn': typeof LearnRoute
  '/live-games': typeof LiveGamesRoute
  '/past-games': typeof PastGamesRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/solo-campaign': typeof SoloCampaignRouteWithChildren
  '/study-board': typeof StudyBoardRoute
  '/game/$id': typeof GameIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/solo-campaign/$id': typeof SoloCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/game-setup'
    | '/learn'
    | '/live-games'
    | '/past-games'
    | '/profile'
    | '/puzzles'
    | '/ranking'
    | '/settings'
    | '/solo-campaign'
    | '/study-board'
    | '/game/$id'
    | '/puzzles/$id'
    | '/solo-campaign/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/game-setup'
    | '/learn'
    | '/live-games'
    | '/past-games'
    | '/profile'
    | '/puzzles'
    | '/ranking'
    | '/settings'
    | '/solo-campaign'
    | '/study-board'
    | '/game/$id'
    | '/puzzles/$id'
    | '/solo-campaign/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/game-setup'
    | '/learn'
    | '/live-games'
    | '/past-games'
    | '/profile'
    | '/puzzles'
    | '/ranking'
    | '/settings'
    | '/solo-campaign'
    | '/study-board'
    | '/game/$id'
    | '/puzzles/$id'
    | '/solo-campaign/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GameSetupRoute: typeof GameSetupRoute
  LearnRoute: typeof LearnRoute
  LiveGamesRoute: typeof LiveGamesRoute
  PastGamesRoute: typeof PastGamesRoute
  ProfileRoute: typeof ProfileRoute
  PuzzlesRoute: typeof PuzzlesRouteWithChildren
  RankingRoute: typeof RankingRoute
  SettingsRoute: typeof SettingsRoute
  SoloCampaignRoute: typeof SoloCampaignRouteWithChildren
  StudyBoardRoute: typeof StudyBoardRoute
  GameIdRoute: typeof GameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-board': {
      id: '/study-board'
      path: '/study-board'
      fullPath: '/study-board'
      preLoaderRoute: typeof StudyBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo-campaign': {
      id: '/solo-campaign'
      path: '/solo-campaign'
      fullPath: '/solo-campaign'
      preLoaderRoute: typeof SoloCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-games': {
      id: '/past-games'
      path: '/past-games'
      fullPath: '/past-games'
      preLoaderRoute: typeof PastGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-games': {
      id: '/live-games'
      path: '/live-games'
      fullPath: '/live-games'
      preLoaderRoute: typeof LiveGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-setup': {
      id: '/game-setup'
      path: '/game-setup'
      fullPath: '/game-setup'
      preLoaderRoute: typeof GameSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo-campaign/$id': {
      id: '/solo-campaign/$id'
      path: '/$id'
      fullPath: '/solo-campaign/$id'
      preLoaderRoute: typeof SoloCampaignIdRouteImport
      parentRoute: typeof SoloCampaignRoute
    }
    '/puzzles/$id': {
      id: '/puzzles/$id'
      path: '/$id'
      fullPath: '/puzzles/$id'
      preLoaderRoute: typeof PuzzlesIdRouteImport
      parentRoute: typeof PuzzlesRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PuzzlesRouteChildren {
  PuzzlesIdRoute: typeof PuzzlesIdRoute
}

const PuzzlesRouteChildren: PuzzlesRouteChildren = {
  PuzzlesIdRoute: PuzzlesIdRoute,
}

const PuzzlesRouteWithChildren =
  PuzzlesRoute._addFileChildren(PuzzlesRouteChildren)

interface SoloCampaignRouteChildren {
  SoloCampaignIdRoute: typeof SoloCampaignIdRoute
}

const SoloCampaignRouteChildren: SoloCampaignRouteChildren = {
  SoloCampaignIdRoute: SoloCampaignIdRoute,
}

const SoloCampaignRouteWithChildren = SoloCampaignRoute._addFileChildren(
  SoloCampaignRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GameSetupRoute: GameSetupRoute,
  LearnRoute: LearnRoute,
  LiveGamesRoute: LiveGamesRoute,
  PastGamesRoute: PastGamesRoute,
  ProfileRoute: ProfileRoute,
  PuzzlesRoute: PuzzlesRouteWithChildren,
  RankingRoute: RankingRoute,
  SettingsRoute: SettingsRoute,
  SoloCampaignRoute: SoloCampaignRouteWithChildren,
  StudyBoardRoute: StudyBoardRoute,
  GameIdRoute: GameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
