/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyBoardRouteImport } from './routes/study-board'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PastGamesRouteImport } from './routes/past-games'
import { Route as LiveGamesRouteImport } from './routes/live-games'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoloCampaignIndexRouteImport } from './routes/solo-campaign.index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as SoloCampaignIdRouteImport } from './routes/solo-campaign.$id'
import { Route as PuzzlesIdRouteImport } from './routes/puzzles.$id'
import { Route as GameIdRouteImport } from './routes/game.$id'

const StudyBoardRoute = StudyBoardRouteImport.update({
  id: '/study-board',
  path: '/study-board',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PastGamesRoute = PastGamesRouteImport.update({
  id: '/past-games',
  path: '/past-games',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveGamesRoute = LiveGamesRouteImport.update({
  id: '/live-games',
  path: '/live-games',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloCampaignIndexRoute = SoloCampaignIndexRouteImport.update({
  id: '/solo-campaign/',
  path: '/solo-campaign/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloCampaignIdRoute = SoloCampaignIdRouteImport.update({
  id: '/solo-campaign/$id',
  path: '/solo-campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIdRoute = PuzzlesIdRouteImport.update({
  id: '/puzzles/$id',
  path: '/puzzles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/learn': typeof LearnRoute
  '/live-games': typeof LiveGamesRoute
  '/past-games': typeof PastGamesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/study-board': typeof StudyBoardRoute
  '/game/$id': typeof GameIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/solo-campaign/$id': typeof SoloCampaignIdRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/solo-campaign': typeof SoloCampaignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/learn': typeof LearnRoute
  '/live-games': typeof LiveGamesRoute
  '/past-games': typeof PastGamesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/study-board': typeof StudyBoardRoute
  '/game/$id': typeof GameIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/solo-campaign/$id': typeof SoloCampaignIdRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/solo-campaign': typeof SoloCampaignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/learn': typeof LearnRoute
  '/live-games': typeof LiveGamesRoute
  '/past-games': typeof PastGamesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/study-board': typeof StudyBoardRoute
  '/game/$id': typeof GameIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/solo-campaign/$id': typeof SoloCampaignIdRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/solo-campaign/': typeof SoloCampaignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/learn'
    | '/live-games'
    | '/past-games'
    | '/play'
    | '/profile'
    | '/ranking'
    | '/settings'
    | '/study-board'
    | '/game/$id'
    | '/puzzles/$id'
    | '/solo-campaign/$id'
    | '/puzzles'
    | '/solo-campaign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/learn'
    | '/live-games'
    | '/past-games'
    | '/play'
    | '/profile'
    | '/ranking'
    | '/settings'
    | '/study-board'
    | '/game/$id'
    | '/puzzles/$id'
    | '/solo-campaign/$id'
    | '/puzzles'
    | '/solo-campaign'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/learn'
    | '/live-games'
    | '/past-games'
    | '/play'
    | '/profile'
    | '/ranking'
    | '/settings'
    | '/study-board'
    | '/game/$id'
    | '/puzzles/$id'
    | '/solo-campaign/$id'
    | '/puzzles/'
    | '/solo-campaign/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LearnRoute: typeof LearnRoute
  LiveGamesRoute: typeof LiveGamesRoute
  PastGamesRoute: typeof PastGamesRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  SettingsRoute: typeof SettingsRoute
  StudyBoardRoute: typeof StudyBoardRoute
  GameIdRoute: typeof GameIdRoute
  PuzzlesIdRoute: typeof PuzzlesIdRoute
  SoloCampaignIdRoute: typeof SoloCampaignIdRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
  SoloCampaignIndexRoute: typeof SoloCampaignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-board': {
      id: '/study-board'
      path: '/study-board'
      fullPath: '/study-board'
      preLoaderRoute: typeof StudyBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-games': {
      id: '/past-games'
      path: '/past-games'
      fullPath: '/past-games'
      preLoaderRoute: typeof PastGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-games': {
      id: '/live-games'
      path: '/live-games'
      fullPath: '/live-games'
      preLoaderRoute: typeof LiveGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo-campaign/': {
      id: '/solo-campaign/'
      path: '/solo-campaign'
      fullPath: '/solo-campaign'
      preLoaderRoute: typeof SoloCampaignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo-campaign/$id': {
      id: '/solo-campaign/$id'
      path: '/solo-campaign/$id'
      fullPath: '/solo-campaign/$id'
      preLoaderRoute: typeof SoloCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/$id': {
      id: '/puzzles/$id'
      path: '/puzzles/$id'
      fullPath: '/puzzles/$id'
      preLoaderRoute: typeof PuzzlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LearnRoute: LearnRoute,
  LiveGamesRoute: LiveGamesRoute,
  PastGamesRoute: PastGamesRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  SettingsRoute: SettingsRoute,
  StudyBoardRoute: StudyBoardRoute,
  GameIdRoute: GameIdRoute,
  PuzzlesIdRoute: PuzzlesIdRoute,
  SoloCampaignIdRoute: SoloCampaignIdRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
  SoloCampaignIndexRoute: SoloCampaignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
